name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::319604804922:role/devops-prod-github-actions-role
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-prod-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update deployment image tag
        run: |
          aws ssm put-parameter \
            --name "/devops-prod/image-tag" \
            --value "${{ github.sha }}" \
            --type "String" \
            --overwrite

      - name: Start Auto Scaling instance refresh
        id: instance-refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name devops-prod-app-asg \
            --preferences '{"MinHealthyPercentage":50,"InstanceWarmup":180}' \
            --query "InstanceRefreshId" \
            --output text)

          echo "refresh_id=$REFRESH_ID" >> "$GITHUB_OUTPUT"

      - name: Wait for instance refresh
        run: |
          REFRESH_ID="${{ steps.instance-refresh.outputs.refresh_id }}"

          for attempt in {1..40}; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name devops-prod-app-asg \
              --instance-refresh-ids "$REFRESH_ID" \
              --query "InstanceRefreshes[0].Status" \
              --output text)

            echo "Instance refresh status: $STATUS"

            if [ "$STATUS" = "Successful" ]; then
              echo "Deployment completed successfully."
              exit 0
            fi

            if [ "$STATUS" = "Failed" ] || \
               [ "$STATUS" = "Cancelled" ] || \
               [ "$STATUS" = "RollbackFailed" ] || \
               [ "$STATUS" = "RollbackSuccessful" ]; then
              echo "Deployment failed with status: $STATUS"
              exit 1
            fi

            sleep 30
          done

          echo "Timed out waiting for instance refresh."
          exit 1